name: Truffle CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g yarn truffle
      - run: yarn install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - run: yarn airdrop
      - run: yarn test
